const bsVariables = {
  // "--bs-blue": ref("#0d6efd"),
  // "--bs-indigo": ref("#6610f2"),
  // "--bs-purple": ref("#6f42c1"),
  // "--bs-pink": ref("#d63384"),
  // "--bs-red": ref("#dc3545"),
  // "--bs-orange": ref("#fd7e14"),
  // "--bs-yellow": ref("#ffc107"),
  // "--bs-green": ref("#198754"),
  // "--bs-teal": ref("#20c997"),
  // "--bs-cyan": ref("#0dcaf0"),
  // "--bs-black": "#000",
  // "--bs-white": "#fff",
  // "--bs-gray": ref("#6c757d"),
  // "--bs-gray-dark": ref("#343a40"),
  // "--bs-gray-100": ref("#f8f9fa"),
  // "--bs-gray-200": ref("#e9ecef"),
  // "--bs-gray-300": ref("#dee2e6"),
  // "--bs-gray-400": ref("#ced4da"),
  // "--bs-gray-500": ref("#adb5bd"),
  // "--bs-gray-600": ref("#6c757d"),
  // "--bs-gray-700": ref("#495057"),
  // "--bs-gray-800": ref("#343a40"),
  // "--bs-gray-900": ref("#212529"),
  // "--bs-primary": ref("#0d6efd"),
  // "--bs-secondary": ref("#6c757d"),
  // "--bs-success": ref("#198754"),
  // "--bs-info": ref("#0dcaf0"),
  // "--bs-warning": ref("#ffc107"),
  // "--bs-danger": ref("#dc3545"),
  // "--bs-light": ref("#f8f9fa"),
  // "--bs-dark": ref("#212529"),
  // "--bs-primary-rgb": "13, 110, 253",
  // "--bs-secondary-rgb": "108, 117, 125",
  // "--bs-success-rgb": "25, 135, 84",
  // "--bs-info-rgb": "13, 202, 240",
  // "--bs-warning-rgb": "255, 193, 7",
  // "--bs-danger-rgb": "220, 53, 69",
  // "--bs-light-rgb": "248, 249, 250",
  // "--bs-dark-rgb": "33, 37, 41",
  // "--bs-primary-text-emphasis": ref("#052c65"),
  // "--bs-secondary-text-emphasis": ref("#2b2f32"),
  // "--bs-success-text-emphasis": ref("#0a3622"),
  // "--bs-info-text-emphasis": ref("#055160"),
  // "--bs-warning-text-emphasis": ref("#664d03"),
  // "--bs-danger-text-emphasis": ref("#58151c"),
  // "--bs-light-text-emphasis": ref("#495057"),
  // "--bs-dark-text-emphasis": ref("#495057"),
  // "--bs-primary-bg-subtle": ref("#cfe2ff"),
  // "--bs-secondary-bg-subtle": ref("#e2e3e5"),
  // "--bs-success-bg-subtle": ref("#d1e7dd"),
  // "--bs-info-bg-subtle": ref("#cff4fc"),
  // "--bs-warning-bg-subtle": ref("#fff3cd"),
  // "--bs-danger-bg-subtle": ref("#f8d7da"),
  // "--bs-light-bg-subtle": ref("#fcfcfd"),
  // "--bs-dark-bg-subtle": ref("#ced4da"),
  // "--bs-primary-border-subtle": ref("#9ec5fe"),
  // "--bs-secondary-border-subtle": ref("#c4c8cb"),
  // "--bs-success-border-subtle": ref("#a3cfbb"),
  // "--bs-info-border-subtle": ref("#9eeaf9"),
  // "--bs-warning-border-subtle": ref("#ffe69c"),
  // "--bs-danger-border-subtle": ref("#f1aeb5"),
  // "--bs-light-border-subtle": ref("#e9ecef"),
  // "--bs-dark-border-subtle": ref("#adb5bd"),
  // "--bs-white-rgb": "255, 255, 255",
  // "--bs-black-rgb": "0, 0, 0",
  // "--bs-font-sans-serif": "system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"",
  // "--bs-font-monospace": "SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace",
  // "--bs-gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0))",
  // "--bs-body-font-family": "var("--bs-font-sans-serif)",
  // "--bs-body-font-size": "1rem",
  // "--bs-body-font-weight": "400",
  // "--bs-body-line-height": "1.5",
  "--bs-body-color": ref("#212529"),
  // "--bs-body-color-rgb": "33, 37, 41",
  "--bs-body-bg": ref("#ffffff"),
  // "--bs-body-bg-rgb": "255, 255, 255",
  // "--bs-emphasis-color": "#000",
  // "--bs-emphasis-color-rgb": "0, 0, 0",
  // "--bs-secondary-color": "rgba(33, 37, 41, 0.75)",
  // "--bs-secondary-color-rgb": "33, 37, 41",
  // "--bs-secondary-bg": ref("#e9ecef"),
  // "--bs-secondary-bg-rgb": "233, 236, 239",
  // "--bs-tertiary-color": "rgba(33, 37, 41, 0.5)",
  // "--bs-tertiary-color-rgb": "33, 37, 41",
  // "--bs-tertiary-bg": ref("#f8f9fa"),
  // "--bs-tertiary-bg-rgb": "248, 249, 250",
  // "--bs-heading-color": "inherit",
  // "--bs-link-color": ref("#0d6efd"),
  // "--bs-link-color-rgb": "13, 110, 253",
  // "--bs-link-decoration": "underline",
  // "--bs-link-hover-color": ref("#0a58ca"),
  // "--bs-link-hover-color-rgb": "10, 88, 202",
  // "--bs-code-color": ref("#d63384"),
  // "--bs-highlight-color": ref("#212529"),
  // "--bs-highlight-bg": ref("#fff3cd"),
  // "--bs-border-width": "1px",
  // "--bs-border-style": "solid",
  "--bs-border-color": ref("#dee2e6"),
  // "--bs-border-color-translucent": "rgba(0, 0, 0, 0.175)",
  // "--bs-border-radius": "0.375rem",
  // "--bs-border-radius-sm": "0.25rem",
  // "--bs-border-radius-lg": "0.5rem",
  // "--bs-border-radius-xl": "1rem",
  // "--bs-border-radius-xxl": "2rem",
  // "--bs-border-radius-2xl": "var("--bs-border-radius-xxl)",
  // "--bs-border-radius-pill": "50rem",
  // "--bs-box-shadow": "0 0.5rem 1rem rgba(0, 0, 0, 0.15)",
  // "--bs-box-shadow-sm": "0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)",
  // "--bs-box-shadow-lg": "0 1rem 3rem rgba(0, 0, 0, 0.175)",
  // "--bs-box-shadow-inset": "inset 0 1px 2px rgba(0, 0, 0, 0.075)",
  // "--bs-focus-ring-width": "0.25rem",
  // "--bs-focus-ring-opacity": "0.25",
  // "--bs-focus-ring-color": "rgba(13, 110, 253, 0.25)",
  // "--bs-form-valid-color": ref("#198754"),
  // "--bs-form-valid-border-color": ref("#198754"),
  // "--bs-form-invalid-color": ref("#dc3545"),
  // "--bs-form-invalid-border-color": ref("#dc3545"),
};

export { bsVariables };
